#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent

# Clean-up the initial TCP ports allocation
agent.deallocate_ports("tcp")
agent.unset_env("TCP_PORT")
agent.unset_env("TCP_PORTS")
agent.unset_env("TCP_PORTS_RANGE")
