#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import sys
import os

if not 'TCP_PORTS' in os.environ:
    sys.exit(0)

agent_id = os.environ['AGENT_ID']
rdb = agent.redis_connect(privileged=True)
domain_port = rdb.hgetall(f'{agent_id}/data/domain_port')

# Versions up to 1.0.2 have a fixed range of 8 ports allocated by the core
# when the module instance is created. They are listed in "TCP_PORTS"
# environment variable. We consider unused ports as "released", so the
# "allocate-ports" procedure can reuse them before asking for new ports to
# the local node.
unused_ports = set(os.environ['TCP_PORTS'].split(",")) - set(domain_port.values())
rdb.sadd(f'{agent_id}/data/released_ports', *unused_ports)

agent.unset_env("TCP_PORT")
agent.unset_env("TCP_PORTS")
agent.unset_env("TCP_PORTS_RANGE")
